---

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install ansible
  shell: amazon-linux-extras install ansible2

- name: Install packages 
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - git
    - "{{java.VERSION}}"

# - name: Install docker
#   yum:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - docker
#     - git

- name: Start Docker
  service:
    name: docker
    state: started

- name: Add user ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Add user jenkins to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Download Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 766

- name: Create symlink to docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Give execute permissions /usr/local/bin/docker-compose
  file:
    dest: /usr/local/bin/docker-compose
    mode: a+x

- name: Get home directory
  set_fact:
    home_dir: "{{ lookup('env', 'HOME') }}"
  
- name: Copy pubkey
  copy:
    src: "{{ home_dir }}/.ssh/id_rsa.pub"
    dest: /home/ec2-user/.ssh/
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Copy keys file
  copy:
    src: ../../../.keys.yml
    dest: "/var/lib/jenkins/workspace/.keys.yml"
    owner: jenkins
    group: jenkins
    mode: '0644'

# - name: Install Java 8 using YUM.
#   yum:
#     name: "{{java.VERSION}}"
#     state: present
#   become: true

- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"

- name: Download Jenkins repo yum URL for  
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import GPG Key
  rpm_key:
    state: present
    key: "{{jenkins.gpg_key}}"

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Change Jenkins JAVA options
  lineinfile: 
    dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{jenkins.JAVA_OPTIONS}}"
  become: true

- name: Start Jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
  loop:
    - github
    - docker-compose-build-step
    - ansible
    - git

- name: Restart service jenkins
  service:
    name: jenkins
    state: restarted
