version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
        - ls
        - pwd
        - docker -v
        - docker-compose -v
        - docker-compose build
        
