version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
        - ls
        - docker -v
        - curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
        
