AWSTemplateFormatVersion: "2010-09-09"  
Resources:  
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-02ccb28830b645a41
      KeyName: aws_devOps
      SecurityGroupIds:
        - sg-0a5b8011c7dc77b39
      SubnetId: subnet-6d9a1121
