version: "3"

services:
  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    command: sh entrypoint.sh
    ports:
      - '8090:8090'
    depends_on:
      - db

  frontend:
    image: node:12-alpine
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
    command: sh -c "yarn && yarn build"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
volumes:
  postgres_data:
