- name: test2
  hosts: localhost
  gather_facts: no
  vars_files:
    - /var/lib/jenkins/workspace/.keys.yml
  tasks:

    - set_fact:
         home_dir: "{{ lookup('env', 'HOME') }}"
      become: true

    - name: Create pubkey
      openssh_keypair:
        path: '{{ home_dir }}/.ssh/id_ssh_rsa'
        public_key: id_ssh_rsa.pub

    - name: Create key pair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: ansible-host-keypair
        key_material: "{{ lookup('file', '{{ home_dir }}/.ssh/id_rsa.pub') }}"

    - name: Get Host info
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "Host"
      register: ec2_host

    - name: Add host private ip to group
      add_host: hostname={{ ec2_host.instances[0].network_interfaces[0].private_ip_address }} groups=ec2host

- hosts: ec2host
  user: ec2-user
  become: true
  gather_facts: no
  tasks:

    - name: Get latest git repo
      git:
        repo: https://github.com/Tiki92/devOps.git
        dest: /home/ec2-user/devOps
    
    - name: Stop docker containers
      shell: docker-compose -f /home/ec2-user/devOps/docker-compose.yml down --volumes
      ignore_errors: yes

    - name: Start all docker containers
      shell: docker-compose -f /home/ec2-user/devOps/docker-compose.yml up -d