
- name: test
  hosts: localhost
  gather_facts: no
  vars_files:
    - .keys.yml
  tasks:
    - set_fact:
         home_dir: "{{ lookup('env', 'HOME') }}"
      become: true

    - name: Create key pair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: ansible-keypair
        key_material: "{{ lookup('file', '{{ home_dir }}/.ssh/id_rsa.pub') }}"

    - name: create a cloudformation stack
      cloudformation:
        aws_access_key: '{{ AWS_ACCESS_KEY_ID }}'
        aws_secret_key: '{{ AWS_SECRET_ACCESS_KEY }}'
        stack_name: "ansible-cloudformation"
        state: "present"
        region: "eu-central-1"
        disable_rollback: true
        template: "devOps_stack.yml"
        tags:
          Stack: "ansible-cloudformation"

    - name: Get Controller Info
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "Controller"
      register: ec2_controller

    - name: Get Host info
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "Host"
      register: ec2_host

    - debug:
        var: ec2_controller.instances[0].network_interfaces[0].association.public_ip
    
    - debug:
        var: ec2_host.instances[0].network_interfaces[0].private_ip_address

    - name: Add controller public IP to group
      add_host: hostname={{ ec2_controller.instances[0].network_interfaces[0].association.public_ip }} groups=ec2controller

    - name: Add host private ip to group
      add_host: hostname={{ ec2_host.instances[0].network_interfaces[0].private_ip_address }} groups=ec2host

- hosts: ec2controller
  user: ec2-user
  become: true
  gather_facts: no
  vars:
    users:
    - jenkins
  tasks:

    - name: Get home directory
      set_fact:
        home_dir: "{{ lookup('env', 'HOME') }}"

    - name: "Create user accounts and add users to groups"
      user:
        name: "{{ item }}"
        groups: "adm,ec2-user"
      with_items: "{{ users }}"

    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '{{ home_dir }}/.ssh/id_rsa.pub') }}"
      with_items: "{{ users }}"

    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers" # path: in version 2.3
        state: "present"
        regexp: "^%adm"
        line: "%adm ALL=(ALL) NOPASSWD: ALL"

- hosts: ec2controller
  user: jenkins
  become: true
  gather_facts: no
  roles:
    - jenkins
  tags: jenkins